Matplotlib created a temporary config/cache directory at /tmp/pbs.2395924[1].pbsha.ib.sockeye/matplotlib-y_lo1f7w because the default path (/home/szhang99/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "faces.py", line 143, in <module>
    clust_ot = kmeans.fit_predict(A[0].cpu())
  File "/home/szhang99/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1122, in fit_predict
    return self.fit(X, sample_weight=sample_weight).labels_
  File "/home/szhang99/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1030, in fit
    X = self._validate_data(X, accept_sparse='csr',
  File "/home/szhang99/.local/lib/python3.8/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/szhang99/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/szhang99/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 644, in check_array
    _assert_all_finite(array,
  File "/home/szhang99/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 96, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
